apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: myapp
        image: monica014/book-service
        envFrom:
        - configMapRef:
            name: dbconfig
        env:
        - name: SERVER_PORT
          value: '8080'
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: ClusterIP
  selector:
    app: book-api
  ports:
  - targetPort: 8080
    port: 80
    

