version: '3.5'

services:
  book-service:             ## This becomes the HOSTNAME and is converted into http://book-service:9001/
    image: monica014/book-service  
    environment:
      - DBSERVER=database-1.cjzgzknditm4.us-east-1.rds.amazonaws.com
      - DBPORT=3306
      - DBNAME=studentbookdb
      - DBUSER=admin
      - SPRING_DATASOURCE_PASSWORD=admin12345
      - SERVER_PORT=8080  # An Example for Overriding Server Port
    
    ports:
      - 50001:8080
    
  student-service:          ## This becomes the HOSTNAME and is converted into http://student-service:9002/
    image: monica014/student-service
    environment:
      - DBSERVER=database-1.cjzgzknditm4.us-east-1.rds.amazonaws.com
      - DBPORT=3306
      - DBNAME=studentbookdb
      - DBUSER=admin
      - SPRING_DATASOURCE_PASSWORD=admin12345
      - BOOK_API=http://book-service:8080 ## Ref Line#4 and #13 [ http://SERVICENAME:PORT]
    ports:
      - 50002:9002
    depends_on:
        - book-service
